In [5]:
import pandas as pd
print("I've downloaded a dataset from " + url + "")
url = "https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2020/2020-05-05/villagers.csv"
data = pd.read_csv(url)
data.isna().sum()
print (data.shape)

I've downloaded a dataset from https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2020/2020-05-05/villagers.csv
(391, 11)

"Variables" are the quantities that are to be recorded, and "observations" are the individual quantities of the corresponding variables.

In [6]:
import pandas as pd

# Load the dataset
url = 'https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2020/2020-05-05/villagers.csv'
data = pd.read_csv(url)

# Overall summary
print("Overall summary:")
print(data.info())

# Summary of numerical columns
print("\nSummary of numerical columns:")
print(data.describe())

# Summary of categorical columns
print("\nSummary of categorical columns:")
categorical_columns = data.select_dtypes(include=['object']).columns
for column in categorical_columns:
    print(f"\n{column}:")
    print(data[column].value_counts())

# Check for missing values
print("\nMissing values:")
print(data.isnull().sum())

Overall summary:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 391 entries, 0 to 390
Data columns (total 11 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   row_n        391 non-null    int64
 1   id           390 non-null    object
 2   name         391 non-null    object
 3   gender       391 non-null    object
 4   species      391 non-null    object
 5   birthday     391 non-null    object
 6   personality  391 non-null    object
 7   song         380 non-null    object
 8   phrase       391 non-null    object
 9   full_id      391 non-null    object
 10  url          391 non-null    object
dtypes: int64(1), object(10)
memory usage: 33.7+ KB
None

Summary of numerical columns:
            row_n
count  391.000000
mean   239.902813
std    140.702672
min      2.000000
25%    117.500000
50%    240.000000
75%    363.500000
max    483.000000

Summary of categorical columns:

id:
id
admiral    1
mott       1
paula      1
patty      1
pate       1
          ..
eloise     1
elmer      1
ellie      1
elise      1
zucker     1
Name: count, Length: 390, dtype: int64

name:
name
Admiral    1
Muffy      1
Paula      1
Patty      1
Pate       1
          ..
Elvis      1
Eloise     1
Elmer      1
Ellie      1
Zucker     1
Name: count, Length: 391, dtype: int64

gender:
gender
male      204
female    187
Name: count, dtype: int64

species:
species
cat          23
rabbit       20
frog         18
squirrel     18
duck         17
dog          16
cub          16
pig          15
bear         15
mouse        15
horse        15
bird         13
penguin      13
sheep        13
elephant     11
wolf         11
ostrich      10
deer         10
eagle         9
gorilla       9
chicken       9
koala         9
goat          8
hamster       8
kangaroo      8
monkey        8
anteater      7
hippo         7
tiger         7
alligator     7
lion          7
bull          6
rhino         6
cow           4
octopus       3
Name: count, dtype: int64

birthday:
birthday
1-27     2
12-5     2
7-31     2
3-26     2
8-3      2
        ..
4-3      1
10-26    1
7-23     1
12-8     1
3-8      1
Name: count, Length: 361, dtype: int64

personality:
personality
lazy      60
normal    59
cranky    55
snooty    55
jock      55
peppy     49
smug      34
uchi      24
Name: count, dtype: int64

song:
song
K.K. Country     10
Forest Life       9
Imperial K.K.     7
K.K. Soul         7
K.K. Ragtime      7
                 ..
Aloha K.K.        2
Drivin'           1
Senor K.K.        1
K.K.  Bazaar      1
K.K. D&B          1
Name: count, Length: 92, dtype: int64

phrase:
phrase
wee one       2
quacko        2
bloop         2
aye aye       1
snoot         1
             ..
lambchop      1
yeah buddy    1
chow down     1
unh-hunh      1
pronk         1
Name: count, Length: 388, dtype: int64

full_id:
full_id
villager-admiral    1
villager-muffy      1
villager-paula      1
villager-patty      1
villager-pate       1
                   ..
villager-elvis      1
villager-eloise     1
villager-elmer      1
villager-ellie      1
villager-zucker     1
Name: count, Length: 391, dtype: int64

url:
url
https://villagerdb.com/images/villagers/thumb/admiral.98206ee.png    1
https://villagerdb.com/images/villagers/thumb/muffy.1497c92.png      1
https://villagerdb.com/images/villagers/thumb/paula.563ba81.png      1
https://villagerdb.com/images/villagers/thumb/patty.3e17f7f.png      1
https://villagerdb.com/images/villagers/thumb/pate.c60838c.png       1
                                                                    ..
https://villagerdb.com/images/villagers/thumb/elvis.57d4757.png      1
https://villagerdb.com/images/villagers/thumb/eloise.112208b.png     1
https://villagerdb.com/images/villagers/thumb/elmer.cc7df52.png      1
https://villagerdb.com/images/villagers/thumb/ellie.5a144a6.png      1
https://villagerdb.com/images/villagers/thumb/zucker.8dbb719.png     1
Name: count, Length: 391, dtype: int64

Missing values:
row_n           0
id              1
name            0
gender          0
species         0
birthday        0
personality     0
song           11
phrase          0
full_id         0
url             0
dtype: int64

An attribute is a variable that belongs to an object, and they are access using dot notation; a method represents the behavior or actions that an object can perform, and it is basically a function